name: where_is_mecca
description: This application shows the direction to Mecca

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  cupertino_icons: ^0.1.2
  equatable: ^1.0.1
  geolocator: ^5.1.5
  flutter_bloc: ^2.0.1
  flutter_compass: 0.2.0
  flutter_screenutil: ^0.6.1
  flutter_svg: ^0.15.0
  sensors: ^0.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family:  QiblaIcons
      fonts:
          - asset: fonts/icons.ttf

    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf
        - asset: fonts/Ubuntu-Bold.ttf

  assets:
    - images/