name: where_is_mecca
description: This application shows the direction to Mecca

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  geolocator: ^5.1.5
  flutter_bloc: ^2.0.1
  flutter_compass: 0.2.0
  flutter_screenutil: ^0.6.1
  flutter_svg: ^0.15.0
  sensors: ^0.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true