/// Flutter icons QuiblaIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  QuiblaIcons
///      fonts:
///       - asset: fonts/QuiblaIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class QiblaIcons {
  QiblaIcons._();

  static const _kFontFam = 'QiblaIcons';

  static const IconData duaHands = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData qibla = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData compass = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData kaaba = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData arrowUp = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData compassTable = const IconData(0xe806, fontFamily: _kFontFam);
}